version: '3'

services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: demo01
    volumes:
      - pg-data:/var/lib/postgresql/data

  back-plato: 
    image: matirodriguezo/back-plato:latest
    build:
      context: ./back-plato
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demo01
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "8884:8884"
    depends_on:
      - postgres

  front-plato: 
    image: matirodriguezo/front-plato:latest
    build:
      context: ./front-plato 
    ports:
      - "9994:9994"
    depends_on:
      - back-plato 

volumes:
  pg-data: