version: '3'

services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: bus
    volumes:
      - pg-data:/var/lib/postgresql/data

  back-plato: 
    image: matirodriguezo/back-bus:latest
    build:
      context: ./back-bus
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bus
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "6789:6789"
    depends_on:
      - postgres

  front-plato: 
    image: matirodriguezo/front-bus:latest
    build:
      context: ./front-bus 
    ports:
      - "9876:9876"
    depends_on:
      - back-bus 

volumes:
  pg-data: