spring.application.name=back-bus
server.port = 6789
logging.file.name = back-bus.log
spring.datasource.url=jdbc:postgresql://localhost:5432/bus
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect